### ISSUE TITLE
Team-V7x

### ISSUE THREAD

**Issue by Mahmoud514** [mahmoud5141/Team-V7x#2]
Traceback (most recent call last):
File "santet.py", line 30, in 
sms_spoof_elk()
File "/data/data/com.termux/files/home/santet-online/core/onlen.py", line 141, in sms_spoof_elk
print r.json()
File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/models.py", line 892, in json
return complexjson.loads(self.text, **kwargs)
File "/data/data/com.termux/files/usr/lib/python2.7/json/init.py", line 339, in loads
return _default_decoder.decode(s)
File "/data/data/com.termux/files/usr/lib/python2.7/json/decoder.py", line 364, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/data/data/com.termux/files/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by mrcix1** [comment]
احلي مسا عليكوا
